---

apiVersion: v1
kind: Service
metadata:
  name: phpinfo
  labels:
    app: leapp-centos6
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP
  selector:
    app: leapp-centos6

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: leapp-centos6
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: leapp-centos6

